Repository dhia1599/ao_rp, pull requests merged in 2024-05, with the labels that each got.

#1 navbar setup
  frontend/package.json
  frontend/public/logo.png
  frontend/src/components/locale/Locale.tsx
  frontend/src/components/navbar.tsx
  frontend/src/components/styled/login.ts
  frontend/src/helpers/locale.ts
  frontend/src/images.d.ts
  frontend/src/index.tsx
  frontend/src/locales/en/index.ts
  frontend/src/locales/en/translation.json
  frontend/src/locales/i18n.ts
  frontend/src/locales/index.ts
  frontend/src/locales/ko/index.ts
  frontend/src/locales/ko/translation.json
  frontend/src/pages/login/Login.tsx
Labels: to review, to merge

#2 Feat/sidebar
  frontend/.eslintrc.json
  frontend/.prettierignore
  frontend/.prettierrc.js
  frontend/src/components/navbar.tsx
  frontend/src/components/sidebar.tsx
  frontend/src/index.tsx
Labels: to review, to merge

#5 logout setup
  frontend/src/App.tsx
  frontend/src/components/logout-button.tsx
  frontend/src/components/navbar.tsx
  frontend/src/components/sidebar.tsx
  frontend/src/index.tsx
Labels: to review

#6 Ap is crud for invoice product
  backend/.env
  backend/src/app.module.ts
  backend/src/entity/invoice.entity.ts
  backend/src/entity/product.entity.ts
  backend/src/migration/CreateInvoiceTable1618951852317.ts
  backend/src/module/client/services/client.service.ts
  backend/src/module/invoice/controllers/invoice.controller.ts
  backend/src/module/invoice/invoice.module.ts
  backend/src/module/invoice/services/invoice.service.ts
  backend/src/module/product/controllers/product.controller.ts
  backend/src/module/product/product.module.ts
  backend/src/module/product/services/product.service.ts
  backend/src/orm.config.ts
  frontend/src/components/sidebar.tsx
  frontend/src/index.tsx
Labels: to review, to merge

#8 Page client with api request
  frontend/package.json
  frontend/src/components/clientItem.tsx
  frontend/src/components/sidebar.tsx
  frontend/src/pages/clients/Client.tsx
  frontend/src/pages/home/Client.tsx
  frontend/src/route.tsx
  frontend/src/services/otherApi.ts
Labels: to merge

#9 Feat/invoices
  backend/.env
  backend/src/entity/client.entity.ts
  backend/src/module/client/services/client.service.ts
  backend/src/module/invoice/services/invoice.service.ts
  frontend/src/assets/img/eye.js
  frontend/src/components/clientItem.tsx
  frontend/src/components/sidebar.tsx
  frontend/src/pages/clients/Client.tsx
  frontend/src/pages/invoices/invoice.tsx
  frontend/src/pages/invoices/invoiceDetails.tsx
  frontend/src/route.tsx
  frontend/src/services/otherApi.ts
Labels: to review
